name: Integration

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint check
        run: npm run lint
      #- name: Get latest JBrowse
      #  run: mkdir .jbrowse && yarn run jbrowse create --force .jbrowse
      #- name: Run unit tests
      #  run: yarn test --passWithNoTests
      #- name: Test plugin
      #  run: yarn run test:e2e
